name: Daily LinkedIn Job Search

on:
  schedule:
    # Run daily at 8:00 AM UTC (adjust timezone as needed)
    - cron: '0 8 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  search-jobs:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright asyncio
        playwright install chromium
        
    - name: Run LinkedIn job search
      env:
        LINKEDIN_EMAIL: ${{ secrets.LINKEDIN_EMAIL }}
        LINKEDIN_PASSWORD: ${{ secrets.LINKEDIN_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        SMTP_EMAIL: ${{ secrets.SMTP_EMAIL }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      run: |
        python linkedin_scraper.py
        
    - name: Upload logs (if needed)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: search-logs
        path: |
          *.log
          search-results-*.json
        retention-days: 7
